### ISSUE TITLE
Moodle documentation

### ISSUE THREAD

**Issue by einhorntee** [BlkPingu/attendion#35]
Add link to repository, link to Heroku and description of project to Moodle ( https://moodle.htw-berlin.de/mod/assign/view.php?id=384359 )

**Comment by BlkPingu** [comment]
Added Text:

> Link zum Repository: https://github.com/BlkPingu/attendion

 

Heroku: https://attendion.herokuapp.com/users/sign_in

 

Attendion ist eine Rails Web-App um sich zu verabreden. Events können erstellt und Nutzer eingeladen werden. Daten werden nur im notwendigsten Rahmen gespeichert 

Die App richtet sich an Menschen die nicht auf Datensammler angewiesen sein wollen und trotzdem vernetzt sein möchten.
