### ISSUE TITLE
Known Bugs

### ISSUE THREAD

**Issue by einhorntee** [BlkPingu/attendion#58]
- [x]  German Devise translations aren't found by livesystem
- [x]  Edit Profile: Changes are not being saved
- [x]  Join Event Link isn't part of the right CSS class
- [x]  ` Logged in asemail` appears on home page and shouldn't
- [x] Creator of event should automatically join event
- [x] Only attributes of events on user page that are filled in should appear on user page
- [x] Show User Profile contains All AttendingEvents. Needs check whether the user has joined any events, then only show events they've joined _!!! SHOULD work but cannot test_
- [x] Show User profile is missing translations for elsif/else cases
- [x] leave event button should only appear for person whose profile it is on

**Comment by BlkPingu** [comment]
german translations had `en:` at top

**Comment by einhorntee** [comment]
Nope, they don't, e.g. `translation missing: de.devise.sessions.user.signed_out` when signing out in German

**Comment by BlkPingu** [comment]
closed
